indent was driving rasys crazy

diff --git a/bin/tests b/bin/tests
--- a/bin/tests
+++ b/bin/tests
@@ -38,6 +38,6 @@ echo ""
 if [ "$failed" -eq "0" ]; then
     echo -e "\e[92mAll tests pass!\e[0m"
 else 
-   echo -e "\e[91mTests have failed!\e[0m exiting with code 1";
-   exit 1;
+    echo -e "\e[91mTests have failed!\e[0m exiting with code 1";
+    exit 1;
 fi
